baseurl                  = "https://epic-heyrovsky-9846bc.netlify.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Ink."
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = ""
    homepage             = "main"                           # What to call the home page link
    footerText           = "Ink."

# Metadata for Open Graph and Twitter
    description          = "An Ink Experiment."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Ink"

[[params.mainMenu]]
    link = "/posts"
    text = "Posts"

[[params.mainMenu]]
    link = "/about"
    text = "About"

[imaging]
    quality = 75